version: '3.8'

services:
  # Single Backend Service for Coolify
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: processmind-backend
    restart: unless-stopped
    ports:
      - "${PORT:-5000}:5000"
    environment:
      # Core settings
      - NODE_ENV=production
      - PORT=5000
      
      # External services (you need to set these in Coolify)
      - REDIS_URL=${REDIS_URL}
      - MONGODB_URI=${MONGODB_URI}
      
      # Required secrets
      - JWT_SECRET=${JWT_SECRET}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      
      # Optional services
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:5001}
      - CORS_ORIGIN=${CORS_ORIGIN:-http://localhost:5001}
      - SMTP_HOST=${SMTP_HOST:-smtp.gmail.com}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_USER=${SMTP_USER:-}
      - SMTP_PASS=${SMTP_PASS:-}
      
      # Storage
      - S3_ACCESS_KEY=${S3_ACCESS_KEY:-}
      - S3_SECRET_KEY=${S3_SECRET_KEY:-}
      - S3_ENDPOINT=${S3_ENDPOINT:-}
      - S3_BUCKET=${S3_BUCKET:-}
      
      # Stripe
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY:-}
      
      # Misc
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - DISABLE_WORKERS=${DISABLE_WORKERS:-false}
      
    volumes:
      - uploads-data:/app/uploads
      - logs-data:/app/logs
    
    # Simple health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  uploads-data:
  logs-data: