name: Deploy to Hetzner VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            # Navigate to project directory
            cd /home/deploy/process-mind
            
            # Pull latest changes
            git pull origin main
            
            # Backend update
            cd backend
            npm install --production
            
            # Frontend build
            cd ../frontend
            npm install
            npm run build
            
            # Copy built files to nginx directory
            sudo cp -r build/* /var/www/processmind/
            
            # Reload PM2 processes with zero downtime
            cd ..
            pm2 reload ecosystem.config.js --env production
            
            # Save PM2 state
            pm2 save
            
            # Optional: Run any database migrations
            # cd backend && npm run migrate
            
            echo "Deployment completed successfully!"